import os

SECRET_KEY = ''
DEBUG = True
DB_USERNAME = ''
DB_PASSWORD = ''
BLOG_DB_NAME = ''
DB_HOST = os.getenv('IP', '')
DB_URI = 'mysql+pymysql://%s:%s@%s/%s' % (DB_USERNAME, DB_PASSWORD, DB_HOST, BLOG_DB_NAME)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
